[pytest]
minversion = 7.0
addopts = -ra -q
testpaths =
	app/tests/dbAccess
	app/tests/viewmodels
	app/tests/services
	app/tests/routers
	app/tests/schemas
	app/tests/models
	app/tests/mappers
	app/tests/core
python_files = test_*.py
python_classes = Test*
python_functions = test_*
filterwarnings =
	ignore:The ``declarative_base\(\)`` function is now available:DeprecationWarning
	ignore:Support for class-based `config` is deprecated:UserWarning
